### ISSUE TITLE
tnt search throw an exception

### ISSUE THREAD

**Issue by aqualaguna** [pvtl/voyager-frontend#15]
im working in my project with this voyager-frontend.
and then i encountered this error:
```
PDOException: SQLSTATE[HY000]: General error: 5 database is locked in /home/forge/**/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php:87 
 Stack trace: 
 #0 /home/forge/**/vendor/teamtnt/tntsearch/src/Indexer/TNTIndexer.php(87): PDO->exec('INSERT INTO inf...') 
 #1 /home/forge/**/vendor/teamtnt/tntsearch/src/TNTSearch.php(371): TeamTNT\TNTSearch\Indexer\TNTIndexer->setStemmer(Object(TeamTNT\TNTSearch\Stemmer\PorterStemmer)) 
 #2 /home/forge/**/vendor/teamtnt/laravel-scout-tntsearch-driver/src/Engines/TNTSearchEngine.php(38): TeamTNT\TNTSearch\TNTSearch->getIndex() 
 #3 /home/forge/**/vendor/laravel/scout/src/Jobs/MakeSearchable.php(43): TeamTNT\Scout\Engines\TNTSearchEngine->update(Object(Illuminate\Database\Eloquent\Collection)) 
 #4 [internal function]: Laravel\Scout\Jobs\MakeSearchable->handle() 
```
the model i worked is not searchable and this thing pop up out of nowhere. this is the model. it throw error when i save it (new Row).
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Storage;

class Attachment extends Model
{
  protected $appends = ['url', 'size', 'type'];
  public function getUrlAttribute()
  {
    return Storage::url("attachment/{$this->name}");
  }
  public function getSizeAttribute()
  {
    return Storage::size("attachment/{$this->name}");
  }
  public function getTypeAttribute()
  {
    return Storage::mimeType("attachment/{$this->name}");
  }
  public function attachable()
  {
    return $this->morphTo();
  }
  public function scopeNoAttachable($q)
  {
    return $q->where('attachable_id', 0);
  }
}

```

**Comment by Jean-PierreGassin** [comment]
Hey @aqualaguna, this doesn't look like it's related to the model you've created but instead to the database you're working with and the Scout driver.

By default the frontend module comes with Laravel Scout and TNTSearch which is a driver for Scout.

Does the database lock disappear after restarting your development environment?

**Comment by Jean-PierreGassin** [comment]
Closing due to a lack of response, if you find you encounter the issue again please feel free to open another issue.
